# Build tuning
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.4.101-hotspot

# Fabric Loom + IntelliJ still has known config cache issues.
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=1.0.3
maven_group=fr.zazac1
mod_id=bottled_levels
archive_base_name=bottledlevels

# Dependencies
fabric_api_version=0.161.0+26.3
