# Build tuning
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-21.0.12.101-hotspot

# Fabric Loom + IntelliJ still has known config cache issues.
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
loom_version=1.17.13

# Mod Properties
mod_version=1.0.1
maven_group=fr.zazac1
mod_id=bottled_levels
archive_base_name=bottledlevels

# Dependencies
fabric_api_version=0.141.4+1.21.11
